### ISSUE TITLE
能否写个多页面的example，演示下？

### ISSUE THREAD

**Issue by Leadrive** [neeboo/dva_dart#1]
谢谢。

**Comment by neeboo** [comment]
@Leadrive 
还在开发中，并不完善，请等待

**Comment by Leadrive** [comment]
加油，能用时，我来测试下。

**Comment by neeboo** [comment]
做了dva_flutter依赖dva_dart，请看flutter的例子

[dva_flutter](https://github.com/neeboo/dva_flutter)

**Comment by Leadrive** [comment]
@neeboo 谢谢，期待你的example
